In [4]:
import numpy as np
import os

# Load data
data = os.path.join(os.getcwd(),'output_results', 'Dagu_rgb_signals.npy')
data = np.load(data)

# Tampilkan isi
print(data.shape)  # Output: (jumlah_frame, 3)
print(data)  # Menampilkan 5 data pertama

(2026, 3)
[[35.46417683 61.02705793 86.57012195]
 [35.44047619 60.7593006  86.02901786]
 [35.53652108 60.90248494 86.16942771]
 ...
 [35.25297619 60.11681548 82.4985119 ]
 [35.13874854 59.94714341 82.06645939]
 [35.41340361 60.34713855 82.71385542]]
